apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wrappedup-prod

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: backend-configmap-patch.yaml
  - path: backend-deployment-patch.yaml
  - target:
      kind: Secret
      name: sonarqube-db-credentials
    patch: |-
      - op: replace
        path: /stringData/password
        value: prod-sonarqube-password  # Replace with actual production password 