apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wrappedup-prod

resources:
  - ../../base
  - ingress.yaml
  - mysql-deployment.yaml
  - mysql-pvc.yaml
  - mysql-pv.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: backend-configmap-patch.yaml
  - path: backend-deployment-patch.yaml 