apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wrappedup-pvc
  namespace: wrappedup-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: mysql-pv-prod 