apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-credentials
  namespace: wrappedup-infra
type: Opaque
stringData:
  username: sonar
  password: changeme  # This should be replaced with actual values in the overlays 