apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: wrappedup-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /opt/sonarqube/data/es7
              chown -R 1000:1000 /opt/sonarqube/data
              chmod -R 700 /opt/sonarqube/data
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/data
          securityContext:
            runAsUser: 0
      containers:
        - name: sonarqube
          image: sonarqube:9.9-community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://sonarqube-db:5432/sonar
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-credentials
                  key: username
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-credentials
                  key: password
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/data
          securityContext:
            runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarqube-data 