apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrappedup-backend
spec:
  template:
    spec:
      containers:
        - name: wrappedup-backend
          image: ghcr.io/guillermorivero/wrappedup-backend:dev
          env:
            - name: CORS_ALLOWED_ORIGINS
              value: "https://wrappedupdev.duckdns.org,http://wrappedupdev.duckdns.org,http://localhost:3000"
            - name: CORS_ALLOWED_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD"
            - name: CORS_ALLOWED_HEADERS
              value: "Authorization,Content-Type,Accept,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers"
            - name: CORS_EXPOSED_HEADERS
              value: "Authorization,Content-Type,Accept,Origin,Access-Control-Allow-Origin,Access-Control-Allow-Credentials"
            - name: CORS_MAX_AGE
              value: "7200"
            # Keep the Spring WebFlux/Web CORS configs for backward compatibility 
            - name: "spring.webflux.cors.allowed-origins"
              value: "https://wrappedupdev.duckdns.org"
            - name: "spring.web.cors.allowed-origins" 
              value: "https://wrappedupdev.duckdns.org"
            - name: "spring.web.cors.allowed-methods"
              value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: "spring.web.cors.allowed-headers"
              value: "Authorization,Content-Type,X-Requested-With,Accept"
            - name: "spring.web.cors.allow-credentials"
              value: "true"
            - name: "jwt.expiration"
              value: "86400000"
---
apiVersion: v1
kind: Service
metadata:
  name: wrappedup-backend-service
spec:
  type: LoadBalancer 