apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-dev
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Using hostPath for development instead of CSI
  hostPath:
    path: /mnt/data/mysql-dev
    type: DirectoryOrCreate 